---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres
  namespace: backend
spec:
  encryptedData:
    POSTGRES_URL: AgAx++cXiy+p+41IKDBsXS6TE/tJokQiHpQH1VBNzKLnhtAqUiAUYxyXZqk2GEafTcq3qlT0AYjTjOZOniIdl4875wyk7sujyFh0Ef4l0aMMe45j4pZKjvS5JKtsF8bubyioxCQuClixnl5Ae8KIkF6v4jusPIRKfJDZ4NrmUlyGShTBsLInck8t77SoVIDx4hCfj3HyXuSZ/9kDQao0S00g/MG7IL4CFlR/L+cGYxbHr+QU1Uz2t6u58AShsioNYKnjN4MsYPJ1viJpj8bjbK8PowzZA6jj2dSJKHV20q1LqyDTelLL6uDT/jrRhn9oVhCT36yF4Bsja9LM7r0f5NBdxcZyDpUYnvFFEQSQlbQlpgzuosamc8pihffKjYxlwqVrY5H/1kxBmMk9R7PArUs2GgoccJ3zYH2tvqm2QVLaVYUnyyY+ciyxMgY4tmD+GPL5WTp0745FXWxpcIDeY5c7JwuWB2MiSfXOwtv4if8b5uOh4Lexe677hcZsaLa/Ei/6LLTlxlFMHSFQ+Tw2Ow6PvxDZ6TqeflQpFn7GGSROgJuKmK4j+sJ84gAd0KiXMRYanKHco9ly2MxwuItR8fzcdz1ZEscr4PsQVZ3ZlOv9WB3eK5ZX78GivBOzAS5pMLvg3XrVQ9XS0TXSGM64Db3YxfnMepdI6//+WMbVKy7LWwYxoJOIM92jIWQHPHR3XbQXou/yOATyxXb8XfznFHJpCN+1p0hk5KCMaVEQ8oF8cvmOpzDBvS/KWROn1UwiTi/8PNKXPnYpVTb+LRxUSpHbaQ5HCSzStn7foUBfIEs4PGlTWhHx/WQfiSE+X0SYKYAGvTrkxX/DzuA3LQmRHjByLSmdjKMh7borLNSd3q24YjRC2TCei0+8Pw==
  template:
    metadata:
      name: postgres
      namespace: backend
