server:
  port: 8080
spring:
  application:
    name: fileserver
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show_sql: true
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: never
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
valkey:
  host: localhost
  port: 6379
aws:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_S3_REGION}
  bucket: ${AWS_S3_BUCKET_NAME}
  cloudfront:
    private-key-path: /cert/aws/aws-cloudfront-private-key.pem